### ISSUE TITLE
Only one Check used

### ISSUE THREAD

**Issue by Zeratul100** [chipik/SAP_RECON#4]
Only first check is performed (with -c option), because of 
return {"status":False, "url":""}
in else clause, that exits the loop
Is it intended to work like that?

**Comment by manasmbellani** [comment]
Hi @Zeratul100, I think @chipik just merged a fix from PR #2 . Try to perform `git pull` in your cloned repo and try running the script again.

**Comment by Zeratul100** [comment]
Yes, now it works better :)
BTW @manasmbellani could you tell me where to put this zip file for download test? (-f )

**Comment by hcrisgnya** [comment]
I got the hint that it works with putting the file into the root (c:\) on windows instance. I can't get it to work on NetWeaver JAVA on unix.
